name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest]
        platform:
          - linux/amd64
          - darwin/amd64
          - windows/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run GoLand CI linters
        uses: golangci/golangci-lint-action@v3

    # Optional steps to build and upload artifacts
    # - name: Build binaries
    #   run: |
    #     GOOS=linux GOARCH=amd64 go build -v -o bin/gosh-linux ./cmd
    #     GOOS=darwin GOARCH=amd64 go build -v -o bin/gosh-macos ./cmd
    #     GOOS=windows GOARCH=amd64 go build -v -o bin/gosh.exe ./cmd

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: gosh-binaries
    #     path: bin/
